services:
  nestjs-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=airbnb
      - MYSQL_TCP_PORT=3306